import Providers from '@/components/Providers'
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import ToggleTheme from '@/components/ToggleTheme'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <Providers>
          <header className='py-6'>
            <nav className='container flex items-center justify-between'>
              <ul className='flex gap-6'>
                <li>
                  <Link href='/'>Home</Link>
                </li>
              </ul>

             <ToggleTheme/>              
            </nav>
          </header>

          <main>{children}</main>

          <footer></footer>
        </Providers>

      </body>
    </html>
  )
}
